trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: $(image-name)

steps:

- script: docker run --rm --privileged multiarch/qemu-user-static:register --reset
  displayName: Run QEMU

- task: Docker@2
  displayName: Build + Push
  inputs:
    containerRegistry: $(docker-hub)
    repository: $(imageName)
    command: buildAndPush
    tags: latest
