trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: $(image-name)

steps:
  - script: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    displayName: Run QEMU

  - script: docker login -u $docker-user -p $docker-token
    displayName: Login into docker
    condition: tags

  - task: Docker@2
    displayName: build an image
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: Dockerfile
    condition: master

  - task: Docker@2
    displayName: Build + Push
    condition: tags
    inputs:
      containerRegistry: $(docker-hub)
      repository: $(imageName)
      command: buildAndPush
      tags: |
        telegram
        bot
        admin
