trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: $(image-name)

steps:
  - script: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    displayName: Run QEMU

  - script: docker build -t $(imageName) .
    displayName: Build only
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - script: docker login -u $docker-user -p $docker-token
    displayName: Login into docker
    condition: ne($(Versioned), 'true')

  - script: |
      docker build -t $(imageName) .
      docker push $(imageName):latest
      docker push $(imageName):$(Build.BuildNumber)
    displayName: Build + Push
    condition: ne($(Versioned), 'true')
