trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: $(image-name)

steps:
  - script: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    displayName: Run QEMU

  - script: docker build -t $(imageName) .
    displayName: Build only
    condition: master

  - script: docker login -u $docker-user -p $docker-token
    displayName: Login into docker
    condition: tags

  - script: |
      $TagArray= git tag -l v*
      $TagName = $TagArray[$TagArray.Count – 1]
      docker build -t $(imageName) .
      docker push $(imageName):latest
      docker push $(imageName):$TagName
    displayName: Build + Push
    condition: tags
