# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: $(image-name)

steps:

- script: docker run --rm --privileged multiarch/qemu-user-static:register --reset
  displayName: Run QEMU

- task: Docker@2
  displayName: build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
  condition: master

- task: Docker@2
  displayName: Build + Push
  condition: tags
  inputs:
    containerRegistry: $(dockerHub)
    repository: $(imageName)
    command: buildAndPush
    tags: |
      telegram
      bot
      admin

